### PR TITLE
Fix tint attribute

### LINKED ISSUE #105: Suggestion: Make another CircleImageView extending AppCompatImageView
`android:tint` isn't working in xml, crashes the app. I suppose this is achievable using AppCompatImageView

### PR DESCRIPTION
**Pull request by colinrtwhite**
Fix the tint attribute and support it on pre-Lollipop. Also remove two deprecated API calls. Fixes #105.

### CODE REVIEW

**Comment by colinrtwhite** [comment]
@hdodenhof Could you take a look at my pull request? Thanks.

**Comment by hdodenhof** [comment]
Thanks for your contribution! The changes you made make this library depend on the appcompat and support libraries and that's actually a sacrifice I'm not willing to make for a minor benefit.

Using `setColorFilter()` you can achieve the same results while keeping the footprint of this library small and on point.

**Comment by hdodenhof** [comment]
While I closed this PR, I used parts of it to fix the NPE on api levels < 21. Thanks!

**Comment by ishaan-khan** [comment]
I am still getting NPE with tint, using the latest library

**Pull request closed without merging**
