### PR TITLE
Add support for selector

### PR DESCRIPTION
**Pull request by hdodenhof**
Quick merge of #25 and #34.

### CODE REVIEW

**Comment by hdodenhof** [comment]
I don't like that the default color filter is overridden in pressed state. Needs work.

**Comment by start141** [comment]
What time will merge this pull?

**Comment by hdodenhof** [comment]
Probably not any time soon. I don't like the current state of it and I currently don't have any time to continue working on it.

**Comment by start141** [comment]
OK, thanks!

**Comment by hdodenhof** [comment]
Not gonna happen.

**Comment by KANGOD** [comment]
Well unfortunately

**Comment by hdodenhof** [comment]
Look at #153 for a workaround.

**Pull request closed without merging**
