### PR TITLE
Added selector to CircleImageView

### PR DESCRIPTION
**Pull request by SimoneBellotti**

### CODE REVIEW

**Comment by jenzz** [comment]
@SimoneBellotti I just realized that after applying your changes any `OnClickListener` set on the view is no longer working.
Replacing `return true;` with `return super.onTouchEvent(event);` in `onTouchEvent(MotionEvent event)` should solve the issue. :wink:

**Comment by SimoneBellotti** [comment]
Yes, you're right! I've forgot it

**Comment by hdodenhof** [comment]
Closing in favor of #35. Please have a look!

**Comment by hdodenhof** [comment]
I don't like that it disables the default color filter in pressed state. Needs work.

**Pull request closed without merging**
